---
- hosts: all
  become: yes
  tasks:
    - name: Criação Usuário Suporte
      ansible.builtin.user:
        name: suporte
        comment: sVAGRAuporte
        uid: 5000
        group: root

