---
- hosts: db
  become: yes
  tasks:
   - name: 'Instalação de Pacotes BD'
     apt:
        pkg:
          - mariadb-server
          - wget
          - zip
          - curl
          - vim
          - python3-mysqldb
        state: present
   - name: 'Download e extração DB'    
     unarchive:
        src: https://github.com/rogerramossilva/devops/raw/master/db.zip
        dest: /tmp
        remote_src: yes